### ISSUE TITLE
[BUG] Clicking on search bar crashes contactbrowser

### ISSUE THREAD

**Issue by j1010001** [muttoni/contract-browser#5]
### Current Behavior

Load the website with no wallet signed in. Click on Search (Using Chrome).
I get: Application error: a client-side exception has occurred (see the browser console for more information).

Console:
TypeError: Cannot read properties of undefined (reading 'length')
    at ellipsify (5356-c8d8a0db86cf6bd5.js?dpl=dpl_3qYcQTkQh2Ky2Ceoumu6W2PGzUQX:1:3099)
    at ContractBadge (1383-3391d9d79f9a1b35.js?dpl=dpl_3qYcQTkQh2Ky2Ceoumu6W2PGzUQX:1:5071)
    at wf (fd9d1056-fbc1fe925c9d26da.js:9:38361)
    at rr (fd9d1056-fbc1fe925c9d26da.js:9:110525)
    at gk (fd9d1056-fbc1fe925c9d26da.js:9:88800)
    at fd9d1056-fbc1fe925c9d26da.js:9:88622
    at Xe (fd9d1056-fbc1fe925c9d26da.js:9:88629)
    at Ye (fd9d1056-fbc1fe925c9d26da.js:9:86274)
    at Ve (fd9d1056-fbc1fe925c9d26da.js:9:36252)
    at Ue (fd9d1056-fbc1fe925c9d26da.js:9:36870)

### Expected Behavior

Search works

### Steps To Reproduce

On chrome, click on search

### Environment

```markdown
- OS: MacOS 14.2.1
- Node: ?
- npm:?
```

### What are you currently working on that this is blocking?

Cannot use contractbrowser

**Comment by muttoni** [comment]
Not able to reproduce on Chrome (no wallet signed in). Can you maybe share any other process/steps you did?

**Comment by j1010001** [comment]
Ok little bit more experimentation shows it is only happening on my chrome with bunch of extensions enabled - on another profile where I only have flow reference wallet extension it is ok. I'll try to isolate which extension is causing this.
